{"name": "test_div_zero", "status": "broken", "statusDetails": {"message": "ZeroDivisionError: division by zero", "trace": "@pytest.mark.exception\n    def test_div_zero():\n>       assert div(2, 0) == None\n\nunit\\test_div.py:23: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\na = 2, b = 0\n\n    def div(a, b):\n>       return a/b\nE       ZeroDivisionError: division by zero\n\nunit\\div.py:7: ZeroDivisionError"}, "start": 1577236597045, "stop": 1577236597048, "uuid": "b052f08c-824f-4c3f-89f3-30227be1adee", "historyId": "15b37b0ef5b421a5842f3a5fd1bde553", "testCaseId": "3ffa0e18b25054bad768365e77e358cd", "fullName": "test_div#test_div_zero", "labels": [{"name": "tag", "value": "exception"}, {"name": "suite", "value": "test_div"}, {"name": "host", "value": "MS-20170607LVPH"}, {"name": "thread", "value": "5016-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_div"}]}