{"name": "test_div_zero_param[0-0-None]", "status": "broken", "statusDetails": {"message": "ZeroDivisionError: division by zero", "trace": "num1 = 0, num2 = 0, exception = None\n\n    @pytest.mark.exception\n    @pytest.mark.parametrize(\"num1, num2,exception\", {\n        (0, 10, None),\n        (10, 0, None),\n        (0, 0, None)\n    })\n    def test_div_zero_param(num1, num2,exception):\n>       assert div(num1, num2) == exception\n\nunit\\test_div.py:60: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\na = 0, b = 0\n\n    def div(a, b):\n>       return a/b\nE       ZeroDivisionError: division by zero\n\nunit\\div.py:7: ZeroDivisionError"}, "parameters": [{"name": "num1", "value": "0"}, {"name": "num2", "value": "0"}, {"name": "exception", "value": "None"}], "start": 1577236597378, "stop": 1577236597379, "uuid": "8e3486cf-265b-4dc2-8d83-e614b435902c", "historyId": "54c472f4527135ed436c667402d23623", "testCaseId": "488092d0a8d10c164aeec01e190a2c7d", "fullName": "test_div#test_div_zero_param", "labels": [{"name": "tag", "value": "exception"}, {"name": "suite", "value": "test_div"}, {"name": "host", "value": "MS-20170607LVPH"}, {"name": "thread", "value": "5016-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_div"}]}